repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  # - id: check-added-large-files
  - id: detect-private-key
- repo: https://github.com/psf/black
  rev: 22.10.0/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html
  hooks:
  - id: black
- repo: https://github.com/hadialqattan/pycln
  rev: v0.0.1-beta.3
  hooks:
  - id: pycln
    args: [--config=pyproject.toml]
# - repo: https://github.com/pre-commit/mirrors-isort
#   rev: ''  # Use the revision sha / tag you want to point at
#   hooks:
#   - id: isort
- repo: https://github.com/pycqa/isort
  rev: 5.5.4
  hooks:
  - id: isort
    files: "\\.(py)$"
    args: [--settings-path=pyproject.toml]
